import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import Footer from "@/components/footer";
import Link from "next/link"; // ← Don't forget this!

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "HisabKitab",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Page Layout */}
        <div className="flex min-h-screen">
          {/* Sidebar */}
          <aside className="w-64 bg-gray-800 text-white p-6 space-y-4">
            <h2 className="text-xl font-bold mb-6">Dashboard</h2>
            <nav className="flex flex-col space-y-2">
              <Link href="/" className="hover:text-yellow-300">Home</Link>
              <Link href="/sell-products" className="hover:text-yellow-300">Sell Products</Link>
              <Link href="/udhar-products" className="hover:text-yellow-300">Udhar Products</Link>
              <Link href="/expense-products" className="hover:text-yellow-300">Expense Products</Link>
              <Link href="/generate-report" className="hover:text-yellow-300">Generate Report</Link>
            </nav>
          </aside>

          

          {/* Main Content */}
          <div className="flex-1 flex flex-col">
            <Header />
            <main className="flex-1 p-6 bg-gray-100">{children}</main>
            <Footer />
            
          </div>
        </div>
      </body>
    </html>
  );
}
